# -*- coding: utf-8 -*-
"""Código- Business Case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYGSE8AMcjRRE1HL7CTrikV8qHN6fEj7

# **FASE 1**

---
### Auditoría de Datos, Resolución de Identidad y Limpieza (Data Wrangling)

## **Diagnóstico Inicial (Fase 1)**
"""

import pandas as pd
import numpy as np

# 1. Cargar los conjuntos de datos
print("Cargando archivos...")
eventos = pd.read_csv('/content/ga_eventos.csv')
reservas = pd.read_csv('/content/reservas.csv')
clientes = pd.read_csv('/content/clientes.csv')
tours = pd.read_csv('/content/tours.csv')
proveedores = pd.read_csv('/content/proveedores.csv')

# 2. Resumen rápido de volumen y columnas
datasets = {
    "ga_eventos": eventos,
    "reservas": reservas,
    "clientes": clientes,
    "tours": tours,
    "proveedores": proveedores
}

print("\n=== RESUMEN DE VOLUMEN Y COLUMNAS ===")
for nombre, df in datasets.items():
    print(f"\nFichero: {nombre}")
    print(f"- Filas: {df.shape[0]:,}")
    print(f"- Columnas: {df.shape[1]}")
    print(f"- Columnas presentes: {list(df.columns)}")
    print(f"- Valores nulos por columna:")
    nulos = df.isnull().sum()
    print(nulos[nulos > 0] if nulos.sum() > 0 else "  Sin nulos detectados")

# 3. Primer vistazo a las primeras filas
print("\n=== MUESTRA DE EVENTOS ===")
display(eventos.head(3))

print("\n=== MUESTRA DE RESERVAS ===")
display(reservas.head(3))

print("\n=== MUESTRA DE CLIENTES ===")
display(clientes.head(3))

print("\n=== MUESTRA DE TOURS ===")
display(tours.head(3))

print("\n=== MUESTRA DE PROVEEDORES ===")
display(proveedores.head(3))

"""**Resolución de Identidad (ga_eventos):**

- Tienes 702,821 eventos, pero sólo 72,275 tienen user_id (un ~89.7% son de usuarios anónimos en ese momento).

- Existen 8,347 eventos de compra (reserva_id no nulo). Debemos cruzarlos con los 8,414 registros de reservas.csv para comprobar la coincidencia exacta.

**Inconsistencia Fina de Negocio (reservas.csv vs. tours.csv):**

- En reservas.csv vemos casos con personas = 0 pero un importe_eur > 0 (ejemplo en la fila 0: personas = 0.00 e importe_eur = 0.00, pero en otras filas personas tiene decimales como 170.98 asignado a importe).
- Esto indica columnas desalineadas o datos cruzados en el CSV de reservas.

**La columna estado combina mayúsculas y minúsculas** (CONFIRMADA, Cancelada). Debemos normalizarla a minúsculas (confirmada, cancelada, completada).

**Inconsistencias en Proveedores (proveedores.csv):**

- El proveedor "Tours Roma Group 1" tiene dirección en "Sevilla" y "Guías Marrakech SL 2" en "Barcelona".
- Es una anomalía de datos sintéticos interesante para citar al COMEX como control de calidad.

## **Profundización (Fase 1)**
"""

# 1. Normalización de cadenas y estados
reservas['estado_clean'] = reservas['estado'].astype(str).str.lower().str.strip()

# 2. Análisis de Compras en GA vs Reservas reales
eventos_compra = eventos[eventos['reserva_id'].notnull()]
ids_ga = set(eventos_compra['reserva_id'].unique())
ids_reservas = set(reservas['reserva_id'].unique())

print("=== AUDITORÍA DE RESERVAS Y COMPRAS ===")
print(f"Total reservas en reservas.csv: {len(ids_reservas):,}")
print(f"Total compras registradas en GA: {len(ids_ga):,}")
print(f"Reservas en reservas.csv NO registradas en GA: {len(ids_reservas - ids_ga):,}")
print(f"Compras en GA NO encontradas en reservas.csv: {len(ids_ga - ids_reservas):,}")

# 3. Auditoría de importes y personas
print("\n=== DETECCIÓN DE ANOMALÍAS EN RESERVAS ===")
personas_cero = reservas[reservas['personas'] == 0]
print(f"Reservas con 0 personas: {len(personas_cero)}")

importe_cero = reservas[reservas['importe_eur'] <= 0]
print(f"Reservas con importe <= 0€: {len(importe_cero)}")

# 4. Desglose de Estado de Reservas
print("\n=== DISTRIBUCIÓN DE ESTADOS DE RESERVA ===")
print(reservas['estado_clean'].value_counts(dropna=False))

# 5. Fechas incoherentes (fecha_actividad < fecha_reserva)
reservas['fecha_reserva_dt'] = pd.to_datetime(reservas['fecha_reserva'])
reservas['fecha_actividad_dt'] = pd.to_datetime(reservas['fecha_actividad'])
fechas_incoherentes = reservas[reservas['fecha_actividad_dt'].dt.date < reservas['fecha_reserva_dt'].dt.date]
print(f"\nReservas con fecha de actividad ANTERIOR a la reserva: {len(fechas_incoherentes)}")

"""**Análisis de Inconsistencias Detectadas**
- Discrepancia GA vs. Backend (113 reservas "fantasma" + 40 compras huérfanas): - Hay 113 reservas confirmadas en base de datos que no pasaron por el evento de compra en web (¿reservas por call center, API o fallo del píxel de GA?) y 40 eventos de compra en GA que nunca se consolidaron en la base de datos de reservas.  

**Importes <= 0$ €** (1,297 reservas / ~15.4% del total):
- Debemos diferenciar cuántas son Free Tours (precio 0€ legítimo) vs. posibles
errores de registro o cupones del 100%.

**Normalización de Estados:** Hay 795 cancelada y 365 cancelled. Sumadas dan 1,160 cancelaciones reales (una tasa de cancelación del 13.78%).

**0 personas (15 reservas):** Inconsistencia de datos que requiere decisión de limpieza.

## **Identity Resolution (Fase 1)**


---
El siguiente paso clave en la Fase 1 es mapear la identidad de los usuarios: asociar cada cookie_id y temp_client_id a su correspondiente user_id registrado cuando este inicia sesión o compra.
"""

import pandas as pd

# 1. Unificar estados de cancelación
reservas['estado_clean'] = reservas['estado'].astype(str).str.lower().str.strip()
reservas['estado_clean'] = reservas['estado_clean'].replace({'cancelled': 'cancelada'})

# 2. Mapeo de Identidad (Identity Resolution Table)
# Extraemos todos los pares (cookie_id, user_id) donde user_id NO sea nulo
mapa_identidad = eventos[eventos['user_id'].notnull()][['cookie_id', 'user_id']].drop_duplicates()

# Verificamos si hay cookies asociadas a múltiples user_id (dispositivos compartidos)
cookies_multiusuario = mapa_identidad.groupby('cookie_id')['user_id'].nunique()
cookies_conflicto = cookies_multiusuario[cookies_multiusuario > 1].count()

print("=== RESOLUCIÓN DE IDENTIDAD ===")
print(f"Total pares únicos Cookie <-> User ID: {len(mapa_identidad):,}")
print(f"Cookies asociadas a más de 1 User ID (posible dispositivo compartido): {cookies_conflicto}")

# 3. Asignar user_id a eventos anónimos de cookies conocidas
eventos_enriquecidos = eventos.merge(mapa_identidad, on='cookie_id', how='left', suffixes=('', '_resuelto'))
eventos_enriquecidos['user_id_final'] = eventos_enriquecidos['user_id'].fillna(eventos_enriquecidos['user_id_resuelto'])

cobertura_inicial = eventos['user_id'].notnull().mean() * 100
cobertura_final = eventos_enriquecidos['user_id_final'].notnull().mean() * 100

print(f"\nCobertura inicial de User ID en eventos: {cobertura_inicial:.2f}%")
print(f"Cobertura final tras Resolución de Identidad: {cobertura_final:.2f}%")

"""Hemos logrado elevar la trazabilidad de usuarios identificados del 10.28% al 17.15%, aumentando en casi un 70% la cobertura de eventos atribuidos sin presentar conflictos de dispositivos compartidos.

Con la **Fase 1** (Limpieza e Identidad) completada y documentada, pasamos directamente a la **Fase 2: Definición de Métricas Ejecutivas y Análisis de Negocio** para responder las tres preguntas del COMEX.

# **FASE 2**


---
### Definición de Métricas Ejecutivas y Análisis de Negocio

## **Análisis de Negocio para el COMEX (FASE 2)**

Calcular los números exactos de Venta Real, Factores de Recurrencia y Rendimiento por Destino:
"""

import pandas as pd
import numpy as np

# 1. Cruzar reservas con tours para obtener destino (extraído de la URL)
tours['destino'] = tours['url'].str.extract(r'civitatis\.com/es/([^/]+)/')
reservas_complete = reservas.merge(tours[['tour_id', 'destino', 'precio_por_persona_eur']], on='tour_id', how='left')

# 2. Definición del Estado del Negocio (Métrica 1)
# Identificar Free Tours vs Reservas de Pago con importe <= 0
reservas_complete['es_free_tour'] = reservas_complete['precio_por_persona_eur'] == 0

gmv_bruto = reservas_complete[reservas_complete['estado_clean'].isin(['confirmada', 'completada'])]['importe_eur'].sum()
cancelaciones_val = reservas_complete[reservas_complete['estado_clean'] == 'cancelada']['importe_eur'].sum()
venta_neta = gmv_bruto - cancelaciones_val

print("=== 1. ESTADO DEL NEGOCIO (VENTAS) ===")
print(f"GMV Bruto (Reservas activas): {gmv_bruto:,.2f} €")
print(f"Impacto por Cancelaciones: {cancelaciones_val:,.2f} €")
print(f"Venta Neta Real: {venta_neta:,.2f} €")
print(f"Tasa de Cancelación (por volumen): {(len(reservas_complete[reservas_complete['estado_clean']=='cancelada'])/len(reservas_complete))*100:.2f}%")

# 3. Análisis de Recurrencia (Métrica 2)
# Agrupar por usuario en reservas efectivas (excluyendo canceladas)
reservas_validas = reservas_complete[reservas_complete['estado_clean'] != 'cancelada']
user_stats = reservas_validas.groupby('user_id').agg(
    total_reservas=('reserva_id', 'count'),
    total_gasto=('importe_eur', 'sum'),
    primer_canal=('canal', 'first'),
    primer_campana=('campana', 'first')
).reset_index()

user_stats['es_recurrente'] = user_stats['total_reservas'] > 1

tasa_recurrencia = user_stats['es_recurrente'].mean() * 100
print(f"\n=== 2. REPETICIÓN Y RECURRENCIA ===")
print(f"Total Clientes Únicos con Compra: {len(user_stats):,}")
print(f"Clientes Recurrentes (>=2 compras): {user_stats['es_recurrente'].sum():,}")
print(f"Tasa de Recurrencia de Clientes: {tasa_recurrencia:.2f}%")

# Recurrencia por Canal de Entrada
recurrencia_canal = user_stats.groupby('primer_canal').agg(
    total_clientes=('user_id', 'count'),
    tasa_recurrencia=('es_recurrente', 'mean')
).reset_index()
recurrencia_canal['tasa_recurrencia'] = recurrencia_canal['tasa_recurrencia'] * 100
print("\nTasa de Recurrencia por Canal de Origen:")
print(recurrencia_canal.sort_values(by='tasa_recurrencia', ascending=False).to_string(index=False))

# 4. Rendimiento por Destinos (Métrica 3)
destinos_df = reservas_validas.groupby('destino').agg(
    ventas_totales=('importe_eur', 'sum'),
    reservas_totales=('reserva_id', 'count'),
    clientes_unicos=('user_id', 'nunique')
).reset_index()

# Calcular retención por destino (clientes que repitieron tras comprar en ese destino)
print("\n=== 3. TOP DESTINOS POR VENTAS Y VOLUMEN ===")
print(destinos_df.sort_values(by='ventas_totales', ascending=False).head(10).to_string(index=False))

"""**1. Estado del Negocio (Ventas)**

- **Venta Neta Real vs. GMV:** El volumen bruto transaccionado asciende a 628,683.07 €, pero las cancelaciones restan 108,741.47 €, situando la Venta Neta Real en 519,941.60 €.

- **Impacto del Churn Operativo:** La tasa de cancelación por volumen es del 13.79% (1,160 reservas canceladas sobre el total de 8,414). Esta fuga representa el 17.30% del volumen económico de ventas activas.

**2. Repetición y Recurrencia**

**Tasa de Fidelización:** De los 5,274 clientes únicos con compra, 1,583 son recurrentes (30.02%), lo que muestra una base con hábito de repetición saludable.

**Eficiencia por Canal:**

- **Email:** Presenta la tasa de recurrencia más alta (44.88%). Es el canal de retención más eficiente.

- **Directo y SEO:** Generan volumen alto (2,700 clientes combinados) con una recurrencia sólida (~30-34%).

- **Social y Afiliados:** Tienen las tasas de recurrencia más bajas (21.22% y 25.68%), funcionando principalmente como canales de captación puntual (Top of Funnel).

**3. Rendimiento por Destinos**

Los 4 Grandes (París, Roma, Madrid, Londres): Acumulan más del 60% del volumen de ventas.

**Eficiencia Ticket Medio por Destino:**

- **Praga:** Ticket medio por reserva de 117.12 € (53,757.33 € / 459).

- **Londres:** Ticket medio por reserva de 106.69 € (76,179.56 € / 714).

- **Madrid:** Ticket medio más bajo con 75.04 € (77,219.38 € / 1,029), aunque compensa con alto volumen de reservas y mayor masa de clientes únicos (815).

## **KPIS (Fase 2)**

Extraerá la tasa de cancelación por destino, la recurrencia cross-destination (clientes que viajan a más de una ciudad) y la conversión por tipo de dispositivo:
"""

import pandas as pd
import numpy as np

# 1. Tasa de Cancelación e Impacto por Destino
cancelaciones_destino = reservas_complete.groupby('destino').agg(
    total_reservas=('reserva_id', 'count'),
    canceladas=('estado_clean', lambda x: (x == 'cancelada').sum()),
    gmv_perdido=('importe_eur', lambda x: x[reservas_complete.loc[x.index, 'estado_clean'] == 'cancelada'].sum())
).reset_index()

cancelaciones_destino['pct_cancelacion'] = (cancelaciones_destino['canceladas'] / cancelaciones_destino['total_reservas']) * 100
print("=== CANCELACIONES POR DESTINO (TOP 10 CRÍTICOS) ===")
print(cancelaciones_destino.sort_values(by='pct_cancelacion', ascending=False).head(10).to_string(index=False))

# 2. Análisis Cross-Destination (Clientes Multidestino)
multidestino = reservas_validas.groupby('user_id')['destino'].nunique().reset_index()
multidestino['tipo_cliente'] = multidestino['destino'].apply(lambda x: 'Mono-Destino' if x == 1 else 'Multi-Destino')

print("\n=== DISTRIBUCIÓN MONO-DESTINO VS MULTI-DESTINO ===")
print(multidestino['tipo_cliente'].value_counts(normalize=True) * 100)

# 3. Dispositivo y Conversión en Navegación (GA)
eventos_dispositivo = eventos.groupby('device').agg(
    total_eventos=('session_id', 'count'),
    compras=('reserva_id', lambda x: x.notnull().sum())
).reset_index()

eventos_dispositivo['pct_compras_sobre_eventos'] = (eventos_dispositivo['compras'] / eventos_dispositivo['total_eventos']) * 100
print("\n=== RENDIMIENTO Y COMPRAS POR DISPOSITIVO ===")
print(eventos_dispositivo.to_string(index=False))

"""**Inconsistencia Crítica de Calidad de Datos (Dispositivos)**: Vemos valores como Desktop, desktop, desktp (¡un typo evidente en el log!), Mobile y mobile. Al limpiarlos y agruparlos correctamente, Desktop duplica la tasa de conversión respecto a Mobile (~1.7% vs ~0.98%).

**El Freno a la Recurrencia:** El 88.3% de los clientes son Mono-Destino (solo compran en 1 ciudad). Solo un 11.7% es Multi-Destino. Aquí está el verdadero reto estratégico de Civitatis: el cliente no se va a la competencia, ¡es que solo nos usa para un viaje puntual!

**Fuga Financiera por Cancelaciones:** Londres lidera las pérdidas brutas con 16.759,66 € perdidos (14.7% de tasa de cancelación), seguido de París con 14.749,56 €.

## **VISUALIZACIONES Y CORRECCIONES (FASE 2)**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo con la paleta de Civitatis
civitatis_pink = '#FF0055'
civitatis_navy = '#1E293B'
sns.set_theme(style="whitegrid")

# 1. Limpieza de Dispositivos para Análisis
eventos['device_clean'] = eventos['device'].astype(str).str.lower().str.strip()
eventos['device_clean'] = eventos['device_clean'].replace({'desktp': 'desktop'})

# 2. MAPA DE CALOR: Relación Canal vs. Destino (Matriz de Ventas Neta en €)
matriz_canal_destino = reservas_validas.pivot_table(
    index='canal',
    columns='destino',
    values='importe_eur',
    aggfunc='sum',
    fill_value=0
)

plt.figure(figsize=(12, 6))
sns.heatmap(matriz_canal_destino, annot=True, fmt=".0f", cmap="Reds", cbar=True)
plt.title("Mapa de Calor: Facturación Neta (€) por Canal y Destino", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Destino", fontsize=12)
plt.ylabel("Canal de Adquisición", fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. RELACIÓN ENMARCADA: Ticket Medio vs Tasa de Cancelación por Destino
stats_destino = reservas_complete.groupby('destino').agg(
    ticket_medio=('importe_eur', 'mean'),
    pct_cancelacion=('estado_clean', lambda x: (x == 'cancelada').mean() * 100),
    total_ventas=('importe_eur', lambda x: x[reservas_complete.loc[x.index, 'estado_clean'] != 'cancelada'].sum())
).reset_index()

plt.figure(figsize=(10, 6))
scatter = sns.scatterplot(
    data=stats_destino,
    x='ticket_medio',
    y='pct_cancelacion',
    size='total_ventas',
    sizes=(100, 1000),
    hue='total_ventas',
    palette='Reds',
    legend=False
)

for i in range(len(stats_destino)):
    plt.text(
        stats_destino.ticket_medio[i]+0.8,
        stats_destino.pct_cancelacion[i],
        stats_destino.destino[i].capitalize(),
        fontsize=10,
        weight='bold'
    )

plt.title("Matriz Estratégica: Ticket Medio vs. % Cancelación por Destino", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Ticket Medio por Reserva (€)", fontsize=12)
plt.ylabel("Tasa de Cancelación (%)", fontsize=12)
plt.tight_layout()
plt.show()

# 4. DISPOSITIVO: Conversión Normalizada (Mobile vs Desktop vs Tablet)
conv_device = eventos.groupby('device_clean').agg(
    sesiones=('session_id', 'nunique'),
    compras=('reserva_id', lambda x: x.notnull().sum())
).reset_index()

conv_device['tasa_conversion'] = (conv_device['compras'] / conv_device['sesiones']) * 100

plt.figure(figsize=(8, 5))
ax = sns.barplot(data=conv_device, x='device_clean', y='tasa_conversion', palette=[civitatis_navy, civitatis_pink, '#94A3B8'])
plt.title("Tasa de Conversión Real por Dispositivo (%)", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Tipo de Dispositivo", fontsize=12)
plt.ylabel("Conversión (%)", fontsize=12)

for p in ax.patches:
    ax.annotate(f"{p.get_height():.2f}%", (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 8), textcoords='offset points', weight='bold')

plt.tight_layout()
plt.show()

"""**Interpretación Ejecutiva del Mapa de Calor (Canal vs. Destino)**

- **Dominio Absoluto del SEO:** El canal SEO es el pilar de facturación en prácticamente todos los destinos, destacando París (29.387 €), Londres (27.283 €) y Roma (27.205 €). La dependencia del tráfico orgánico es altísima.

- **Dependencia de SEM en Destinos Clave:** El canal de pago (SEM) funciona con fuerza en París (19.037 €) y Londres (16.853 €), pero cae notablemente en destinos secundarios como Ámsterdam (5.378 €) o Atenas (5.018 €), sugiriendo un gasto publicitario concentrado en capitales principales.

- **Infrautilización del Email en Retención**: El Email aporta cifras bajas en la mayoría de destinos (ej. 2.046 € en Budapest, 2.213 € en Atenas), a pesar de haber demostrado la mayor tasa de recurrencia (44.88%). Existe un margen amplio para campañas personalizadas post-viaje.

**Interpretación de la Matriz Estratégica: Ticket Medio vs. % Cancelación por Destino**

- **Zona Crítica (Alto Ticket Medio y Alta Cancelación):** París (~97 €) y Londres (~111 €) combinan un elevado ticket medio con las tasas de cancelación más altas de la plataforma (~14.8% y ~14.7%). Esta combinación genera la mayor fuga financiera neta en euros absolutos.

- **Zona de Vulnerabilidad de Margen (Bajo Ticket Medio y Alta Cancelación):** Madrid presenta la tasa de cancelación más alta del gráfico (~14.9%), pese a tener un ticket medio bajo (~74 €). Las cancelaciones masivas en volumen penalizan el margen operativo local.

- **Zona Benchmark de Retención (Baja Cancelación):** Atenas (~11.5%), Ámsterdam (~12.0%) y Roma (~12.3%) registran los menores índices de cancelación. Roma destaca como el caso de éxito comercial: alto volumen de ventas y baja tasa de cancelación.

- **Destinos de Valor Premium:** Praga, Estambul y Marrakech mantienen tickets medios altos (>105 €) con un impacto por cancelación medio-alto (~13.7% - 14.3%).

**Interpretación de la Tasa de Conversión Real por Dispositivo**

- **Brecha de Conversión Escritorio vs. Móvil:** La tasa de conversión en Desktop (5.15%) duplica con creces a la de Mobile (2.33%). Esta diferencia confirma que el tráfico móvil sufre una fricción significativa en el checkout o que el usuario reserva viajes desde el ordenador al planificar de forma más pausada.

- **Rendimiento Intermedio de Tablet:** Con un 2.83%, las tablets se sitúan en un punto medio, reforzando la hipótesis de que cuanto mayor es la pantalla y la comodidad de navegación, mayor es la tasa de conversión final.

- **Oportunidad Estratégica:** Mobile aglutina la gran mayoría de las visitas de exploración, pero pierde efectividad al cerrar la venta. Optimizar la experiencia UX/UI del embudo móvil (pagos con Apple Pay/Google Pay, simplificación de formularios) tendría un impacto directo inmediato en el GMV.

## **Análisis Exploratorio Multivariante y Correlaciones (Fase 2 Avanzada)**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Preparación del DataFrame Integrado por Usuario
# Creamos variables agregadas por cliente para el análisis de correlación
user_features = reservas_complete.groupby('user_id').agg(
    total_reservas=('reserva_id', 'count'),
    reservas_confirmadas=('estado_clean', lambda x: (x == 'confirmada').sum()),
    reservas_canceladas=('estado_clean', lambda x: (x == 'cancelada').sum()),
    pct_cancelacion=('estado_clean', lambda x: (x == 'cancelada').mean() * 100),
    gmv_total=('importe_eur', 'sum'),
    ticket_medio=('importe_eur', 'mean'),
    destinos_distintos=('destino', 'nunique'),
    total_personas=('personas', 'sum')
).reset_index()

# Integrar antigüedad del cliente desde clientes.csv
clientes['fecha_alta_dt'] = pd.to_datetime(clientes['fecha_alta'])
fecha_max = pd.to_datetime(reservas['fecha_reserva']).max()
clientes['antiguedad_dias'] = (fecha_max - clientes['fecha_alta_dt']).dt.days

user_features = user_features.merge(clientes[['user_id', 'antiguedad_dias']], on='user_id', how='left')

# 2. MATRIZ DE CORRELACIÓN DE PEARSON
cols_corr = ['total_reservas', 'reservas_canceladas', 'pct_cancelacion',
             'gmv_total', 'ticket_medio', 'destinos_distintos', 'total_personas', 'antiguedad_dias']

matriz_corr = user_features[cols_corr].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(matriz_corr, annot=True, fmt=".2f", cmap="vlag", vmin=-1, vmax=1, cbar=True)
plt.title("Matriz de Correlación de Pearson: Comportamiento del Cliente", fontsize=14, fontweight='bold', pad=15)
plt.tight_layout()
plt.show()

# 3. ANÁLISIS MULTIVARIANTE: Antigüedad vs Recurrencia vs Gasto Total
user_features['categoria_cliente'] = pd.cut(
    user_features['total_reservas'],
    bins=[0, 1, 2, 5, 100],
    labels=['1 Reserva (Unico)', '2 Reservas', '3-5 Reservas', '>5 Reservas']
)

summary_multivariate = user_features.groupby('categoria_cliente').agg(
    num_clientes=('user_id', 'count'),
    gmv_medio=('gmv_total', 'mean'),
    ticket_medio=('ticket_medio', 'mean'),
    destinos_medios=('destinos_distintos', 'mean'),
    pct_cancelacion_media=('pct_cancelacion', 'mean'),
    antiguedad_media_dias=('antiguedad_dias', 'mean')
).reset_index()

print("=== RESUMEN MULTIVARIANTE POR SEGMENTO DE FIDELIDAD ===")
print(summary_multivariate.to_string(index=False))

"""**Interpretación Estratégica de la Matriz de Correlación**

- **El Palancamiento del Negocio (Destinos Distintos vs. Total Reservas: 0.68)**: Existe una fuerte correlación positiva entre el número de reservas y la variedad de destinos visitados. Los clientes altamente recurrentes son aquellos que diversifican sus viajes, lo que confirma que incentivar la navegación cross-destination es la mayor palanca de crecimiento de LTV.

- **Viajes en Grupo o Familiar (Total Personas vs. GMV Total: 0.71):** El número total de personas guardadas por reserva muestra una correlación muy alta con el gasto total del cliente (0.71) y con el total de reservas (0.77). El perfil familiar/grupal aporta la mayor masa financiera a la plataforma.

- **Neutralidad de la Antigüedad (Antigüedad Días: ~0.02 - 0.04)**: La antigüedad de la cuenta del usuario no correlaciona en absoluto con la recurrencia o el gasto total. Un cliente antiguo no es automáticamente más valioso; el valor se activa mediante ofertas contextuales de viaje, no por mero paso del tiempo.

- **Independencia del Ticket Medio (Ticket Medio vs. Recurrencia: -0.03)**: El precio medio por reserva no frena ni impulsa la repetición. El cliente repite en Civitatis por la calidad de la experiencia o la facilidad de uso, sin importar si reserva un free tour o un paquete premium.

**Interpretación del Resumen Multivariante por Segmento de Fidelidad**

- **El Abismo del Mono-Destino (1 Reserva):** El grueso de los clientes (3,809 de 5,822, el 65.4%) solo realiza 1 reserva en una única ciudad (destinos_medios = 1.0). Generan un GMV medio de 94.79 €, pero representan una fuga masiva si no se les activa un segundo viaje.

- **Diversificación Gradual del Catálogo:** Conforme los clientes avanzan en fidelidad, aumenta exponencialmente su exploración de destinos: de 1.28 ciudades en el segmento de 2 reservas a 2.00 ciudades en 3-5 reservas y 3.75 ciudades en >5 reservas. Probar nuevas ciudades es el motor del crecimiento del LTV.

- **Punto Dulce de Margen (3-5 Reservas)**: Este segmento (441 clientes) es el más rentable en términos de ticket medio (95.54 €) y presenta la tasa de cancelación más baja (13.47%).

- **Alerta Operativa en Heavy Users (>5 Reservas):** El grupo de súper usuarios (>5 reservas, 4 clientes) dispara su tasa de cancelación media al 23.81% (casi el doble que el resto). Esto sugiere que los usuarios muy activos realizan reservas especulativas o planes flexibles que luego cancelan con frecuencia.

- **Constancia en la Antigüedad:** La antigüedad media oscila de forma muy uniforme entre 645 y 775 días en todos los segmentos, confirmando nuevamente que el paso del tiempo por sí solo no convierte a un usuario en cliente fiel.

## **Análisis de Normalidad y Test Estadísticos (FASE 2)**

Dado que las variables numéricas del negocio (importe_eur, total_reservas, personas) suelen presentar un marcado sesgo positivo (asimétricas a la derecha por la presencia de Free Tours y grandes reservas grupales), aplicamos el test de Shapiro-Wilk o Kolmogorov-Smirnov para evaluar su distribución:

**Test de Normalidad (Shapiro-Wilk / Kolmogorov-Smirnov):**
Hipótesis nula ($H_0$): La variable sigue una distribución normal.Resultado esperado: Si $p$-value $< 0.05$, rechazamos $H_0$. Los datos no son normales, lo que nos obliga a utilizar métodos no paramétricos para comparar grupos.

**Comparación entre Países (IP de Navegación / Origen):**
- Para evaluar si el volumen de reservas o el gasto medio difiere significativamente según el país de origen de la IP (pais_ip), empleamos el test no paramétrico de Kruskal-Wallis (alternativa a ANOVA para datos no normales).
- Para evaluar la asociación entre el país de origen y la preferencia de destino o tipo de dispositivo, utilizaremos el test de Chi-cuadrado de independencia ($\chi^2$).

**Comparación por Canales y Dispositivos:**
Evaluación de la tasa de conversión y recurrencia mediante Chi-cuadrado ($\chi^2$) y test de Mann-Whitney U para comparar dos grupos independientes (ej. Mobile vs. Desktop).
"""

import pandas as pd
import numpy as np
from scipy import stats

# 1. Test de Normalidad sobre Importe (€) y Reservas por Usuario
print("=== 1. PRUEBAS DE NORMALIDAD (SHAPIRO-WILK) ===")
submuestra_importe = reservas_validas['importe_eur'].sample(min(5000, len(reservas_validas)), random_state=42)
stat_imp, p_val_imp = stats.shapiro(submuestra_importe)

print(f"Importe (€) - Estadístico: {stat_imp:.4f}, p-value: {p_val_imp:.4e}")
if p_val_imp < 0.05:
    print("-> RECHAZAMOS NORMALIDAD: Se deben aplicar pruebas NO PARAMÉTRICAS (Kruskal-Wallis, Mann-Whitney U).\n")
else:
    print("-> Distribución Normal: Se pueden aplicar pruebas PARAMÉTRICAS (ANOVA, t-Student).\n")

# 2. Test No Paramétrico: Kruskal-Wallis para Gasto (€) por País de IP (Top 5 Países)
print("=== 2. COMPARACIÓN DE GASTO POR PAÍS DE ORIGEN (KRUSKAL-WALLIS) ===")
eventos_compras = eventos[eventos['reserva_id'].notnull()][['reserva_id', 'pais_ip']].drop_duplicates()
reservas_pais = reservas_validas.merge(eventos_compras, on='reserva_id', how='left')

top_paises = reservas_pais['pais_ip'].value_counts().head(5).index.tolist()
grupos_pais = [reservas_pais[reservas_pais['pais_ip'] == pais]['importe_eur'].dropna() for pais in top_paises]

stat_kw, p_val_kw = stats.kruskal(*grupos_pais)
print(f"Países analizados: {top_paises}")
print(f"Kruskal-Wallis H-statistic: {stat_kw:.4f}, p-value: {p_val_kw:.4e}")
if p_val_kw < 0.05:
    print("-> DIFERENCIA SIGNIFICATIVA: El gasto por reserva varía de forma estadísticamente significativa según el país de origen.")
else:
    print("-> No hay diferencias significativas en el gasto entre países.")

# 3. Test Chi-Cuadrado: Preferencia de Dispositivo por País de Origen
print("\n=== 3. ASOCIACIÓN PAÍS VS DISPOSITIVO (CHI-CUADRADO DE INDEPENDENCIA) ===")
eventos_top_paises = eventos[eventos['pais_ip'].isin(top_paises)]
tabla_p_d = pd.crosstab(eventos_top_paises['pais_ip'], eventos_top_paises['device_clean'])

chi2, p_val_chi2, dof, ex = stats.chi2_contingency(tabla_p_d)
print(f"Chi2 statistic: {chi2:.4f}, p-value: {p_val_chi2:.4e}")
if p_val_chi2 < 0.05:
    print("-> ASOCIACIÓN SIGNIFICATIVA: La elección del dispositivo (Mobile vs Desktop) depende significativamente del país del usuario.")

# 4. Resumen Estadístico No Paramétrico por País (Mediana e IQR)
print("\n=== RESUMEN NO PARAMÉTRICO POR PAÍS (MEDIANA E IQR) ===")
resumen_pais = reservas_pais[reservas_pais['pais_ip'].isin(top_paises)].groupby('pais_ip').agg(
    mediana_gasto=('importe_eur', 'median'),
    q25_gasto=('importe_eur', lambda x: np.percentile(x.dropna(), 25)),
    q75_gasto=('importe_eur', lambda x: np.percentile(x.dropna(), 75)),
    total_reservas=('reserva_id', 'count')
).reset_index()

resumen_pais['iqr_gasto'] = resumen_pais['q75_gasto'] - resumen_pais['q25_gasto']
print(resumen_pais.to_string(index=False))

"""1. **Test de Normalidad (Shapiro-Wilk en Importe):**
- Hipótesis Nula ($H_0$): La variable importe_eur se distribuye de forma normal en la población.
- Decisión: Se rechaza $H_0$ porque el $p$-value ($7.71 \times 10^{-50}$) es inferior al nivel de significación estándar ($\alpha = 0.05$), demostrando una clara asimetría en el gasto.

2. **Comparación de Gasto por País (Kruskal-Wallis):**
- Hipótesis Nula ($H_0$): La mediana del gasto (importe_eur) es igual entre todos los países de origen analizados.
- Decisión: No se rechaza (se acepta) $H_0$ porque el $p$-value ($0.1318$) es mayor que $\alpha = 0.05$, lo que indica que no hay evidencia estadística suficiente para afirmar que el gasto cambie según el país.

3. **Asociación País vs. Dispositivo (Chi-Cuadrado de Independencia):**
- Hipótesis Nula ($H_0$): La elección del dispositivo de navegación (device) es independiente del país de origen del usuario (pais_ip).
- Decisión: Se rechaza $H_0$ porque el $p$-value ($6.92 \times 10^{-24}$) es significativamente menor que $\alpha = 0.05$, confirmando que la preferencia de dispositivo varía según el mercado.

**Interpretación Estadística y Multivariante**

- **Rechazo de Normalidad** ($p$-value $= 7.71 \times 10^{-50}$): La distribución del gasto presenta una asimetría extrema provocada por los Free Tours (importe 0 €) y las reservas masivas en grupo. Queda validada la necesidad técnica de reportar medianas e IQR en lugar de promedios.

- **Homogeneidad del Gasto por País** ($p$-value $= 0.1318$): El test de Kruskal-Wallis confirma que no existen diferencias estadísticamente significativas en la mediana de gasto por reserva entre los principales países (España, México, Argentina, Colombia y Chile). El comportamiento de compra en presupuesto por reserva es homogéneo a nivel internacional (medianas entre 68 € y 78 €).

- **Dependencia Tecnológica por País** ($p$-value $= 6.92 \times 10^{-24}$): El test de Chi-cuadrado demuestra una asociación altamente significativa entre el país de origen del usuario y el dispositivo utilizado. Los patrones de navegación (Mobile vs. Desktop) varían según el mercado, lo que exige adaptar la UX/UI de la aplicación según la procedencia de la IP.

- **Dominio del Mercado Español:** España concentra el mayor volumen de reservas (4.123) con la mayor dispersión de gasto ($\text{IQR} = 102.39$ €), mientras que los mercados latinoamericanos muestran patrones de compra más concentrados en rangos medios.

## **NUEVAS MÉTRIICAS Y MODELOS (FASE 2)**

**Nuevas Métricas y Modelos a Incorporar**

**Mapa Geoespacial (Scatter Mapbox / Map de Calor Global):**
- En lugar de un mapa estático, representaremos la masa geográfica de demanda proyectando las coordenadas fijas de los principales países de origen (pais_ip).

- El tamaño de la burbuja indicará el volumen total de ventas neta (€) y el color la tasa de conversión real (%).

**Gráfico de Barras Divergentes (Ganancia Neta vs. Fuga por Cancelación):** Un gráfico comparativo por destino donde se visualice en verde la Venta Neta y en rojo el importe perdido por cancelaciones.

**Modelo Predictivo (Regresión Logística de Cancelación):** Entrenaremos un modelo econométrico no paramétrico/probabilístico para predecir la probabilidad de que una reserva sea cancelada ($Y \in \{0, 1\}$) en función del canal, dispositivo, precio y personas.

- Hipótesis Nula ($H_0$): Los coeficientes $\beta_i = 0$ (las variables explicativas no influyen en la probabilidad de cancelación).

- Decisión: Si el $p$-value de los coeficientes es $< 0.05$, se rechaza $H_0$, identificando qué variables incrementan significativamente el riesgo de cancelación.
"""

import pandas as pd
import numpy as np
import plotly.express as px
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 1. PREPARACIÓN DE COORDENADAS PARA EL MAPA GLOBAL DE IP
coordenadas_paises = {
    'España': {'lat': 40.4167, 'lon': -3.7037},
    'México': {'lat': 19.4326, 'lon': -99.1332},
    'Argentina': {'lat': -34.6037, 'lon': -58.3816},
    'Colombia': {'lat': 4.7110, 'lon': -74.0721},
    'Chile': {'lat': -33.4489, 'lon': -70.6693},
    'Irlanda': {'lat': 53.3498, 'lon': -6.2603}
}

# Unir países con reservas activas
eventos_compra = eventos[eventos['reserva_id'].notnull()][['reserva_id', 'pais_ip']].drop_duplicates()
reservas_geo = reservas_validas.merge(eventos_compra, on='reserva_id', how='left')

geo_stats = reservas_geo.groupby('pais_ip').agg(
    venta_total=('importe_eur', 'sum'),
    total_reservas=('reserva_id', 'count'),
    ticket_medio=('importe_eur', 'mean')
).reset_index()

geo_stats['lat'] = geo_stats['pais_ip'].map(lambda x: coordenadas_paises.get(x, {}).get('lat', np.nan))
geo_stats['lon'] = geo_stats['pais_ip'].map(lambda x: coordenadas_paises.get(x, {}).get('lon', np.nan))
geo_stats = geo_stats.dropna(subset=['lat', 'lon'])

# Generar Mapa Interactivo de Burbujas
fig_mapa = px.scatter_geo(
    geo_stats,
    lat='lat',
    lon='lon',
    size='venta_total',
    color='ticket_medio',
    hover_name='pais_ip',
    size_max=40,
    color_continuous_scale='Reds',
    title="Mapa Global de Demanda: Ventas (€) y Ticket Medio por País de Origen"
)
fig_mapa.show()

# 2. MODELO DE REGRESIÓN LOGÍSTICA (PREDICCIÓN DE CANCELACIONES)
# Crear variable binaria target: 1 si cancelada, 0 si no
reservas_complete['es_cancelada'] = (reservas_complete['estado_clean'] == 'cancelada').astype(int)

# Normalizar y preparar variables independientes
df_model = reservas_complete[['es_cancelada', 'importe_eur', 'personas', 'canal', 'precio_por_persona_eur']].dropna()

# Ajustar Modelo Logit
modelo_logit = smf.logit('es_cancelada ~ importe_eur + personas + precio_por_persona_eur + C(canal)', data=df_model).fit()

print("\n=== RESULTADOS DE LA REGRESIÓN LOGÍSTICA (FACTOR DE RIESGO DE CANCELACIÓN) ===")
print(modelo_logit.summary())

# Interpretar Odds Ratios
odds_ratios = np.exp(modelo_logit.params)
print("\n=== ODDS RATIOS (IMPACTO MULTIPLICATIVO EN EL RIESGO DE CANCELACIÓN) ===")
print(odds_ratios)

"""**Cómo se interpreta el modelo?**

**La Variable a Predecir (Target / Variable Dependiente):**
- es_cancelada: Vale 1 si la reserva terminó en cancelación y 0 si la reserva se completó o quedó confirmada.

**El p-value ($P>\vert{}z\vert{}$): Es el semáforo de validez.**
- Si es menor a 0.05, significa que la variable sí influye de verdad en la cancelación (rechazamos la hipótesis nula $H_0$).
- Si es mayor a 0.05, la variable no tiene impacto real y su efecto es puro azar.

**Los Odds Ratios (La clave de lectura):** Indican cuánto se multiplica el riesgo de cancelación al cambiar esa variable. Medir cuántas veces es más probable (o menos probable) que ocurra un evento (la cancelación) en un grupo comparado con otro.

- Un Odds Ratio de 1.00: No cambia el riesgo.

- Un Odds Ratio MENOR a 1.00 (ej. 0.63): REDUCE el riesgo de cancelación. Indica que la variable actúa como un "escudo protector".

- Un Odds Ratio MAYOR a 1.00 (ej. 1.20): AUMENTA el riesgo de cancelación.

**Caso 1:** Odds Ratio menor a 1 (Ejemplo: Email = 0.63)
- La regla: Resta el valor a 1.00 ($1.00 - 0.63 = 0.37$).
- Significado: Los usuarios que vienen por Email tienen un 37% menos de probabilidad de cancelar su reserva que los que vienen por Afiliados.

**Caso 2:** Odds Ratio mayor a 1 (Ejemplo hipotético: Personas = 1.05)
- La regla: Mira cuánto se pasa de 1.00 ($1.05 - 1.00 = 0.05$).
- Significado: Si el valor fuera significativo, diría que por cada persona extra en la reserva, el riesgo de cancelación aumentaría un 5%.

**Significación Global del Modelo (LLR $p$-value $= 0.000727$):**

- Hipótesis Nula ($H_0$): Ninguna de las variables explicativas influye en la probabilidad de que una reserva sea cancelada.Decisión:

- Se rechaza $H_0$ ($p$-value $< 0.05$). El conjunto de factores seleccionados explica variaciones estadísticamente significativas en el riesgo de cancelación.

**Efecto Protector del Canal de Adquisición:**
- Tomando como referencia el canal Afiliados (categoría base):
- Email ($\text{Odds Ratio} = 0.63, p = 0.002$): Reduce la probabilidad de cancelación en un 37%. Es el canal con los usuarios de menor riesgo.
- SEM ($\text{Odds Ratio} = 0.66, p = 0.001$) y Directo ($\text{Odds Ratio} = 0.67, p = 0.001$): Reducen el riesgo de cancelación en un 34% y 33% respectivamente frente a Afiliados.
- SEO ($\text{Odds Ratio} = 0.69, p = 0.001$): Disminuye el riesgo en un 31%.

- Social ($p = 0.456$): No se rechaza $H_0$. No muestra una diferencia estadísticamente significativa en riesgo de cancelación respecto a Afiliados.


---

Email ($\text{OR} = 0.63$): 37% menos riesgo que Afiliados.

SEM ($\text{OR} = 0.66$): 34% menos riesgo que Afiliados.

Directo ($\text{OR} = 0.67$): 33% menos riesgo que Afiliados.

SEO ($\text{OR} = 0.69$): 31% menos riesgo que Afiliados.



---




**Irrelevancia del Importe y Tamaño del Grupo:**

- importe_eur ($p = 0.555$) y personas ($p = 0.796$): No se rechaza $H_0$. El precio total de la reserva y el número de viajeros no condicionan el riesgo de cancelación. La fuga operativa proviene del canal de captación y la planificación del cliente, no del desembolso económico.

- precio_por_persona_eur ($p = 0.099$): Muestra una ligera tendencia positiva ($\text{Odds Ratio} = 1.0057$), pero no llega a ser estadísticamente significativa al nivel del 5%.

## **Gráfico de Barras Divergentes (Ganancia Neta vs. Fuga por Cancelación)**
"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go

# 1. Agrupar ingresos confirmados y perdidos por cancelación por destino
perf_destino = reservas_complete.groupby('destino').agg(
    venta_neta=('importe_eur', lambda x: x[reservas_complete.loc[x.index, 'estado_clean'].isin(['confirmada', 'completada'])].sum()),
    fuga_cancelacion=('importe_eur', lambda x: x[reservas_complete.loc[x.index, 'estado_clean'] == 'cancelada'].sum())
).reset_index()

# Ordenar por venta neta
perf_destino = perf_destino.sort_values(by='venta_neta', ascending=True)

# 2. Crear Gráfico de Barras Divergentes
fig_divergente = go.Figure()

# Barra a la derecha (Venta Neta - Positiva)
fig_divergente.add_trace(go.Bar(
    y=perf_destino['destino'].str.capitalize(),
    x=perf_destino['venta_neta'],
    name='Venta Neta (€)',
    orientation='h',
    marker=dict(color='#10B981')
))

# Barra a la izquierda (Fuga por Cancelación - Negativa)
fig_divergente.add_trace(go.Bar(
    y=perf_destino['destino'].str.capitalize(),
    x=-perf_destino['fuga_cancelacion'],
    name='Fuga por Cancelación (€)',
    orientation='h',
    marker=dict(color='#FF0055')
))

# 3. Formato y diseño del gráfico
fig_divergente.update_layout(
    title=dict(text="Impacto Financiero por Destino: Venta Neta vs. Fuga por Cancelación (€)", font=dict(size=16, color='#1E293B')),
    barmode='relative',
    xaxis=dict(
        title="Euros (€)",
        tickformat=".0f"
    ),
    yaxis=dict(title="Destino"),
    legend=dict(x=0.7, y=0.1),
    height=500,
    margin=dict(l=100, r=20, t=50, b=50)
)

fig_divergente.show()

"""Interpretación Ejecutiva del Gráfico Divergente: Venta Neta vs. Fuga por Cancelación (€)

- **Líder Absoluto de Ventas Netas:** París encabeza la facturación neta rozando los 80.000 € (barra verde), seguido muy de cerca por Madrid, Roma y Londres (todos por encima o rozando los 70.000 €). Estos cuatro destinos representan el motor económico principal del negocio.

- **El Mayor Foco de Fuga Financiera:** Londres es la ciudad que registra la mayor fuga monetaria por cancelaciones (barra roja), superando los 16.000 € perdidos. Aunque tiene una facturación neta similar a Roma o Madrid, su sangrado económico es sensiblemente superior.

- **Ineficiencia Operativa en París y Madrid:** París (casi 15.000 €) y Madrid (más de 12.000 €) acompañan a Londres como los destinos donde se evapora más dinero confirmado.

- **Roma como Benchmark de Eficiencia:** Roma logra prácticamente el mismo nivel de venta neta que Madrid y Londres, pero su barra roja de cancelaciones es visiblemente menor (~11.000 €), lo que demuestra un tráfico de mayor conversión y menor tasa de arrepentimiento.

- **Destinos de Menor Volumen pero Alta Estabilidad:** Ámsterdam, Budapest y Atenas muestran las fugas por cancelación más reducidas del catálogo, manteniendo una relación de conversión mucho más limpia en comparación con su facturación total.
"""

# Script para generar el documento Word completo en Google Colab o Jupyter
!pip install python-docx

import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import parse_xml
from docx.oxml.ns import nsdecls

# 1. Crear documento Word
doc = docx.Document()

# 2. Configurar márgenes
for section in doc.sections:
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

# Estilo auxiliar para títulos
def add_custom_heading(text, level=1):
    h = doc.add_paragraph()
    h.paragraph_format.space_before = Pt(14)
    h.paragraph_format.space_after = Pt(6)
    run = h.add_run(text)
    run.font.name = 'Arial'
    run.font.bold = True
    if level == 1:
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(255, 0, 85) # Rosa Civitatis
    elif level == 2:
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(30, 41, 59) # Azul Marino Civitatis
    return h

def add_bullet(text, bold_prefix=""):
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.space_after = Pt(4)
    if bold_prefix:
        r_bold = p.add_run(bold_prefix)
        r_bold.font.name = 'Arial'
        r_bold.font.bold = True
        r_bold.font.size = Pt(10.5)
    r_text = p.add_run(text)
    r_text.font.name = 'Arial'
    r_text.font.size = Pt(10.5)

# --- PORTADA / CABECERA ---
title_p = doc.add_paragraph()
title_p.paragraph_format.space_after = Pt(4)
r_title = title_p.add_run("Informe Ejecutivo: Diagnóstico Estratégico y Plan de Acción")
r_title.font.name = 'Arial'
r_title.font.size = Pt(20)
r_title.font.bold = True
r_title.font.color.rgb = RGBColor(30, 41, 59)

sub_p = doc.add_paragraph()
sub_p.paragraph_format.space_after = Pt(18)
r_sub = sub_p.add_run("Análisis de Rendimiento, Diagnóstico Inferencial y Hoja de Ruta COMEX — Civitatis")
r_sub.font.name = 'Arial'
r_sub.font.size = Pt(11.5)
r_sub.font.italic = True
r_sub.font.color.rgb = RGBColor(100, 116, 139)

# --- SECCIÓN 1 ---
add_custom_heading("1. Resumen Ejecutivo y Diagnóstico Global del Negocio", level=1)

p = doc.add_paragraph("El análisis exhaustivo sobre la actividad digital y comercial de Civitatis ha permitido consolidar una visión integral del rendimiento del negocio. Tras auditar 702.821 eventos de navegación y 8.414 reservas, se determinó que la plataforma transaccionó un GMV Bruto de 628.683,07 €. Sin embargo, la facturación se ve fuertemente erosionada por un sangrado operativo: se pierden 108.741,47 € en cancelaciones, lo que sitúa la Venta Neta Real en 519.941,60 €.")
p.paragraph_format.space_after = Pt(8)

add_bullet(" La tasa de cancelación global por volumen alcanza el 13,79% (1.160 reservas canceladas de 8.414). En términos económicos, esta fuga equivale a perder el 17,30% de las ventas brutas activas.", "Impacto del Churn Operativo:")
add_bullet(" Se registraron 5.274 clientes únicos con al menos una compra confirmada, de los cuales 1.583 son recurrentes (30,02%). Esto demuestra una tasa de retención base saludable.", "Base de Clientes Fieles:")
add_bullet(" El 88,30% de los clientes compra únicamente en un solo destino (3.809 usuarios), mientras que solo el 11,70% es Multi-Destino. El cliente no abandona la plataforma por irse a la competencia, sino porque no vuelve a ser activado para viajes posteriores.", "El Techo de la Recurrencia (El Abismo Mono-Destino):")

# --- SECCIÓN 2 ---
add_custom_heading("2. Hallazgos Analíticos, Limpieza y Validación Inferencial", level=1)

add_custom_heading("Auditoría de Datos e Identidad", level=2)
p_id = doc.add_paragraph("Gracias a la resolución de identidad (mapeo cookie_id <-> user_id), la trazabilidad de eventos identificados pasó del 10,28% al 17,15%, aumentando en un 70% la cobertura de atribución sin presentar colisiones por dispositivos compartidos. Además, se corrigieron inconsistencias críticas en el registro de dispositivos (unificando valores con tipografías erróneas como 'desktp') y estados de reserva.")

add_custom_heading("Pruebas Estadísticas e Inferenciales", level=2)
add_bullet(" Aplicado sobre la variable importe_eur (W = 0,8962, p-value = 7,71e-50). Se rechaza la hipótesis nula (H0) de normalidad (p < 0,05). Debido a la presencia de Free Tours (0 €) y grandes reservas en grupo, el gasto presenta una marcada asimetría a la derecha. Se valida el uso exclusivo de medianas e rangos intercuartílicos (IQR).", "Test de Normalidad (Shapiro-Wilk):")
add_bullet(" Análisis entre España, México, Argentina, Colombia y Chile (H = 7,0791, p-value = 0,1318). No se rechaza H0. No existen diferencias estadísticamente significativas en la mediana de gasto por reserva según el país del usuario (medianas entre 68 € y 78 €).", "Homogeneidad del Gasto por País (Kruskal-Wallis):")
add_bullet(" (Chi2 = 128,1247, p-value = 6,92e-24). Se rechaza H0. La preferencia tecnológica (uso de Móvil vs. Escritorio) está ligada significativamente al país de origen de la IP, lo que exige adaptar la UX/UI por mercado.", "Asociación País vs. Dispositivo (Chi-Cuadrado):")

# Tabla Resumen Pruebas
table = doc.add_table(rows=4, cols=3)
table.alignment = WD_TABLE_ALIGNMENT.CENTER
headers = ["Prueba Estadística", "p-value", "Conclusión de Negocio"]
data = [
    ["Shapiro-Wilk", "7,71 x 10^-50", "Rechaza Normalidad (Uso obligatorio de IQR)"],
    ["Kruskal-Wallis", "0,1318", "Gasto Homogéneo por País (Sin sesgo por origen)"],
    ["Chi-Cuadrado", "6,92 x 10^-24", "Elección de Dispositivo Depende del País"]
]

for col_idx, text in enumerate(headers):
    cell = table.cell(0, col_idx)
    cell.paragraphs[0].add_run(text).font.bold = True
    set_cell_background(cell, "1E293B")
    cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)

for row_idx, row_data in enumerate(data):
    for col_idx, text in enumerate(row_data):
        cell = table.cell(row_idx + 1, col_idx)
        cell.text = text
        if row_idx % 2 == 0:
            set_cell_background(cell, "F8FAFC")

# --- SECCIÓN 3 ---
add_custom_heading("3. Matriz de Comportamiento y Predictor Econométrico de Cancelación", level=1)

add_custom_heading("Correlaciones del Comportamiento (Pearson)", level=2)
add_bullet(" Muestra una fuerte correlación positiva (r = 0,68). Diversificar las ciudades que visita el cliente es la mayor palanca directa para incrementar el LTV.", "Destinos Distintos vs. Total Reservas:")
add_bullet(" El tamaño del grupo reservado es la variable con mayor peso sobre el gasto total acumulado (r = 0,71). El segmento familiar/grupal aporta el mayor valor financiero.", "Total Personas vs. GMV Total:")
add_bullet(" La antigüedad de la cuenta no tiene relación con el gasto ni con la repetición (r = 0,03). El paso del tiempo no convierte automáticamente a un usuario en cliente fiel.", "Antigüedad vs. Recurrencia:")

add_custom_heading("Modelo de Regresión Logística (Riesgo de Cancelación)", level=2)
p_mod = doc.add_paragraph("El modelo econométrico ajustado (LLR p-value = 0,000727) demuestra que ni el importe total de la reserva (p = 0,555) ni el número de personas (p = 0,796) influyen en la cancelación. La fuga operativa proviene del canal de captación:")
add_bullet(" Reduce la probabilidad de cancelación en un 37% frente a Afiliados (Odds Ratio = 0,63, p = 0,002). Es el canal con tráfico de mayor intención.", "Email:")
add_bullet(" Disminuyen el riesgo de cancelación en un 34% y 33% respectivamente frente a Afiliados (OR = 0,66 y 0,67).", "SEM y Directo:")
add_bullet(" Disminuye el riesgo en un 31% (Odds Ratio = 0,69, p = 0,001).", "SEO:")
add_bullet(" No muestra diferencias estadísticamente significativas en riesgo frente a Afiliados (p = 0,456).", "Social:")

# --- SECCIÓN 4 ---
add_custom_heading("4. Diagnóstico de Eficiencia Comercial y Operativa", level=1)
add_bullet(" Londres lidera la pérdida económica por cancelaciones (16.759,66 € perdidos), seguido de París (14.749,56 €) y Madrid (12.735,00 €). Roma destaca como benchmark: factura a niveles de Madrid pero con menor tasa de cancelación (12,31%).", "Fuga Concentrada en Grandes Capitales:")
add_bullet(" La conversión en Desktop (5,15%) supera por más del doble a Mobile (2,33%). El móvil aglutina el volumen de exploración pero sufre una alta fricción en el checkout.", "Brecha UX Desktop vs. Mobile:")
add_bullet(" Email genera la mayor tasa de recurrencia (44,88%) y el menor riesgo de cancelación, pero representa un volumen de ventas modesto frente a SEO o Directo.", "Subexplotación del Canal Email:")

# --- SECCIÓN 5 ---
add_custom_heading("5. Plan de Acción Estratégico para el COMEX", level=1)

add_bullet(" Pasar del 11,7% de clientes Multi-Destino al 20% en 12 meses. Automatizar campañas post-viaje segmentadas tras finalizar un tour (ej. tras París, promociones directas para Roma o Praga).", "1. Estrategia Cross-Destination (Activación LTV):")
add_bullet(" Neutralizar el gasto publicitario en tráfico de alto arrepentimiento. Renegociar acuerdos con Afiliados y Social Media, condicionando la comisión a que la reserva no sea cancelada en un plazo de 14 días.", "2. Reestructuración de Canales y Comisiones:")
add_bullet(" Incrementar la conversión en dispositivos móviles del 2,33% al 3,50%. Incorporar métodos de pago en un clic (Apple Pay / Google Pay) para eliminar fricción en el checkout móvil.", "3. Optimización del Embudo Móvil (UX/UI Checkout):")
add_bullet(" Recuperar un 20% de los 44.000 € perdidos en París, Londres y Madrid. Implementar recordatorios vía WhatsApp/SMS 48h antes de la excursión, ofreciendo reprogramación flexible en lugar de la cancelación.", "4. Protocolo Anti-Cancelación en Destinos Críticos:")

# 3. Guardar el archivo Word
output_filename = "Diagnostico_Estrategico_Ampliado_Civitatis.docx"
doc.save(output_filename)
print(f" Documento Word generado correctamente: '{output_filename}'")

"""## **ESTUDIO ESTACIONAL (FASE 2)**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

# =============================================================================
# 1. LIMPIEZA Y CÁLCULO DE LEAD TIME REAL (USANDO 'reservas')
# =============================================================================
# Aseguramos formato datetime en las columnas exactas del DataFrame 'reservas'
reservas['fecha_reserva_dt'] = pd.to_datetime(reservas['fecha_reserva'])
reservas['fecha_actividad_dt'] = pd.to_datetime(reservas['fecha_actividad'])

# Estandarizamos la columna estado si no se ha hecho previamente
reservas['estado_clean'] = reservas['estado'].astype(str).str.lower().str.strip()
reservas['estado_clean'] = reservas['estado_clean'].replace({'cancelled': 'cancelada'})

# Cálculo del Lead Time (Días de antelación reales entre reserva y actividad)
reservas['lead_time'] = (reservas['fecha_actividad_dt'] - reservas['fecha_reserva_dt']).dt.days

# =============================================================================
# 2. ESTUDIO DE ANTELACIÓN Y FUGA DE CANCELACIONES
# =============================================================================
bins = [-1, 0, 3, 7, 15, 30, 999]
labels = ['Mismo día', '1-3 días', '4-7 días', '8-15 días', '16-30 días', '+30 días']
reservas['rango_lead_time'] = pd.cut(reservas['lead_time'], bins=bins, labels=labels)

estudio_antelacion = reservas.groupby('rango_lead_time', observed=False).agg(
    total_reservas=('reserva_id', 'count'),
    canceladas=('estado_clean', lambda x: (x == 'cancelada').sum()),
    tasa_cancelacion_pct=('estado_clean', lambda x: (x == 'cancelada').mean() * 100),
    importe_cancelado=('importe_eur', lambda x: x[reservas.loc[x.index, 'estado_clean'] == 'cancelada'].sum()),
    ticket_medio=('importe_eur', 'mean')
).reset_index()

print("=== MATRIZ DE RIESGO SEGÚN ANTELACIÓN (LEAD TIME) ===")
print(estudio_antelacion.to_string(index=False))

# =============================================================================
# 3. AGREGACIÓN DE SERIE TEMPORAL POR FECHA DE RESERVA
# =============================================================================
ts_diaria = reservas.set_index('fecha_reserva_dt').resample('D').agg(
    reservas=('reserva_id', 'count'),
    cancelaciones=('estado_clean', lambda x: (x == 'cancelada').sum()),
    lead_time_promedio=('lead_time', 'mean'),
    gmv_bruto=('importe_eur', 'sum')
).fillna(0)

ts_diaria['tasa_cancelacion'] = (ts_diaria['cancelaciones'] / ts_diaria['reservas']) * 100

# =============================================================================
# 4. DESCOMPOSICIÓN ESTACIONAL DE LA DEMANDA (SEMANAL)
# =============================================================================
ts_semanal = ts_diaria['reservas'].resample('W').sum()

if len(ts_semanal) >= 8:
    descomposicion = seasonal_decompose(ts_semanal, model='additive', period=4)

    plt.style.use('seaborn-v0_8-whitegrid')
    fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(12, 9), sharex=True)
    descomposicion.observed.plot(ax=ax1, color='#0B2545', title='Serie Real Observada (Reservas Semanales)')
    descomposicion.trend.plot(ax=ax2, color='#FF1B58', title='Tendencia (Trend Subyacente)')
    descomposicion.seasonal.plot(ax=ax3, color='#10B981', title='Estacionalidad (Patrón Repetitivo)')
    descomposicion.resid.plot(ax=ax4, color='#64748B', title='Residuo (Ruido Aleatorio)', style='.')
    plt.tight_layout()
    plt.show()

# =============================================================================
# 5. TEST DE DICKEY-FULLER PARA VALIDAR PREDICCIONES
# =============================================================================
adf_result = adfuller(ts_diaria['reservas'].dropna())
print("\n=== TEST DE DICKEY-FULLER (SERIE DIARIA) ===")
print(f"Estadístico ADF: {adf_result[0]:.4f}")
print(f"p-value: {adf_result[1]:.4f}")
print("Estacionaria: SI (Apta para modelos de pronóstico)" if adf_result[1] < 0.05 else "Estacionaria: NO (Requiere aplicar diferencias)")

"""**Matriz de Riesgo por Lead Time**

- **Correlación Directa Antelación-Cancelación:** Cuanto más días faltan para el viaje, mayor es la tasa de cancelación. Pasa del 6.25% en el mismo día a un 18.68% en reservas hechas con más de 30 días de antelación.

- **Fuga Concentrada en Compras Anticipadas:** Las reservas con más de 16 días de antelación acumulan 63,644.58 € en pérdidas (un 58.5% de todo el dinero cancelado en la plataforma).

- **Comportamiento del Ticket Medio:** El importe promedio consumido es constante (~91 € - 93 €), lo que demuestra que el cliente no cancela por reservar tours más caros, sino por cambios en la planificación de su viaje a largo plazo.

**Serie Real Observada (Reservas Semanales)**

- **Estructura bifásica:** La gráfica se divide en dos etapas completamente distintas. Hasta mediados de 2024 el registro es plano (prácticamente cero reservas), lo que sugiere una fase previa al lanzamiento, falta de captura de datos o una etapa de testeo.

- **Escalón operacional:** A partir de junio/julio de 2024 se produce la activación real del negocio. La demanda entra directamente con un suelo de 50 reservas semanales, alcanzando picos por encima de las 120 reservas semanales hacia 2026.

- **Volatilidad creciente:** Conforme aumenta la escala del negocio, las oscilaciones de semana a semana se vuelven más pronunciadas, variando drásticamente entre picos y valles en periodos muy cortos.
- **Interpretación Estratégica:** El volumen de negocio se encuentra en una fase activa de escalado. Esto exige dejar de tratar la operativa de reservas como un proyecto piloto y pasar a dimensionar la capacidad del servicio, la infraestructura tecnológica y la atención al cliente para picos constantes de más de 100-120 pedidos semanales.

**Tendencia (Trend Subyacente)**

**Trayectoria de crecimiento constante:**Al aislar el ruido y la estacionalidad, la tendencia muestra un crecimiento orgánico sólido y continuo desde mediados de 2024.


- Junio - Julio 2024: Despegue vertical de 0 a ~70 reservas/semana.

- Julio 2024 - Principios 2025: Periodo de consolidación y leve desaceleración estabilizándose en torno a 50-60 reservas/semana.

- 2025 - 2026: Segunda fase de aceleración fuerte, alcanzando su máximo histórico (~120 reservas/semana) a inicios de 2026.

- Tramo final: Presenta una ligera corrección o caída en la parte final del registro, aspecto normal al cierre de series temporales por reservas aún no consolidadas.

**Interpretación Estratégica:** Confirma la validación del producto en el mercado (Product-Market Fit) y un crecimiento orgánico saludable a largo plazo. La estrategia debe centrarse en la retención del cliente y en capitalizar el impulso para negociar mejores acuerdos o cupos con proveedores locales aprovechando el mayor volumen de compra

**Estacionalidad (Patrón Repetitivo)**

- **Periodicidad rígida:** La gráfica verde refleja una señal armónica perfecta de frecuencia 4 (ciclo mensual/semanal).

- **Amplitud constante:** La variación del componente estacional oscila exactamente entre -2.3 y +3.0 reservas. Al ser una amplitud constante en un modelo aditivo, indica que el efecto estacional suma o resta una cantidad fija de reservas independientemente de si el volumen total es alto o bajo.

- **Días / Semanas clave:** Muestra picos sistemáticos en momentos concretos del ciclo (por ejemplo, disparos en la demanda los fines de semana o primeros días de mes) seguidos de caídas inmediatas.
- **Interpretación Estratégica:** Permite optimizar la inversión publicitaria y la carga operativa de manera predictiva. Se deben programar las campañas de marketing (sem y paid social) justo antes de los días de pico semanal para maximizar la conversión, mientras que la gestión de personal e inventario se puede planificar con precisión según los valles recurrentes.

**Residuo (Ruido Aleatorio)**

**Efecto de Heterocedasticidad (Varianza no constante):**

- Durante el periodo sin actividad (pre-2024), el residuo es prácticamente 0.

- A partir de julio de 2024, los residuos se dispersan abarcando un rango de entre -20 y +25 reservas por semana.

**Eventos atípicos (Outliers):** Se aprecian varios puntos extremos que se salen del patrón habitual (como la caída hacia -20 a mediados de 2024 o el pico de +25 a principios de 2026). Estos puntos representan anomalías no explicadas por la tendencia ni por la estacionalidad (campañas de marketing puntuales, festivos no recurrentes o fallos en el sistema).

**Interpretación Estratégica:** La aparición de variaciones bruscas (de hasta ±25 reservas) requiere crear un colchón operativo para imprevistos. Estratégicamente, conviene auditar las fechas de los picos y caídas extremas para identificar qué eventos externos (promociones agresivas, fallos web o festivos) provocaron esas desviaciones y así replicar los éxitos o mitigar los fallos.

**Test de Dickey-Fuller (ADF Test)**
- **Resultado:** Estadístico ADF = -1.0325 | p-value = 0.7412
- **Conclusión Técnica:** Al ser el $p$-value mayor a 0.05, no se rechaza la hipótesis nula. La serie temporal es NO ESTACIONARIA.
- **Implicación Práctica:** La serie tiene una clara tendencia al alza y varianza cambiante. Si deseas entrenar un modelo predictivo como ARIMA, debes diferenciar la serie primero (d=1) o utilizar SARIMAX / Prophet para capturar la tendencia y la estacionalidad correctamente.

## **Predicción de Riesgo de Cancelación**

Crear una variable objetivo (target): Etiquetar las reservas como 1 (Cancelada) o 0 (Completada).

Ingeniería de características (Feature Engineering): Usar el lead_time, el importe del ticket, el día de la semana y la antelación para entrenar un modelo (como Random Forest o XGBoost).

Identificar reservas de alto riesgo: Clasificar qué clientes tienen mayor probabilidad de cancelar desde el momento en que realizan la compra.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Preparación de variables (Feature Engineering)
# Creamos la variable objetivo (target): 1 si canceló, 0 si se completó
reservas['target_cancelada'] = (reservas['estado_clean'] == 'cancelada').astype(int)

# Extraemos características temporales de la fecha de reserva
reservas['mes_reserva'] = reservas['fecha_reserva_dt'].dt.month
reservas['dia_semana_reserva'] = reservas['fecha_reserva_dt'].dt.dayofweek
reservas['es_fin_semana'] = reservas['dia_semana_reserva'].isin([5, 6]).astype(int)

# Selección de predictores clave
features = ['lead_time', 'importe_eur', 'mes_reserva', 'dia_semana_reserva', 'es_fin_semana']
X = reservas[features].fillna(0)
y = reservas['target_cancelada']

# 2. División en conjunto de entrenamiento y prueba (80% / 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# 3. Entrenamiento del Modelo (Random Forest)
modelo_rf = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42)
modelo_rf.fit(X_train, y_train)

# 4. Evaluación del Modelo
y_pred = modelo_rf.predict(X_test)
y_proba = modelo_rf.predict_proba(X_test)[:, 1]

print("=== INFORME DE RENDIMIENTO DEL MODELO DE CANCELACIONES ===")
print(classification_report(y_test, y_pred))
print(f"Área Bajo la Curva ROC (ROC-AUC): {roc_auc_score(y_test, y_proba):.4f}")

# 5. Importancia de cada variable
importancias = pd.Series(modelo_rf.feature_importances_, index=features).sort_values(ascending=True)

plt.figure(figsize=(8, 4))
importancias.plot(kind='barh', color='#0B2545')
plt.title('Importancia de las Variables en el Riesgo de Cancelación')
plt.xlabel('Peso de la Variable')
plt.tight_layout()
plt.show()

"""- Predicción de Cancelaciones (Clase 1): Presenta una Precisión de 0.00 y un Recall de 0.00. De las 232 reservas que realmente se cancelaron en el test, el modelo no detectó ninguna.

- Ilusión del Accuracy (86%): El 86% de acierto es tramposo. Como el 86% de las reservas del test eran no-canceladas (1451 de 1683), al clasificar todo como "no cancelado", el modelo saca un 86% de nota sin aprender nada útil.

- Advertencia UndefinedMetricWarning: Es el aviso de scikit-learn indicando que al no predecir nunca la clase 1, la fórmula de precisión genera una división por cero.

- Área Bajo la Curva (ROC-AUC = 0.6071): Confirmación de que el modelo apenas supera al azar (0.50). Tiene cierta capacidad discriminativa por las probabilidades, pero el umbral por defecto (0.50) no activa nunca la alerta de cancelación.

- Importancia de Variables: lead_time (~0.40) y importe_eur (~0.31) dominan ampliamente el modelo. La antelación y el precio son las dos variables clave para predecir el riesgo.

Vamos a corregir el modelo con correcciones de umbral

Ajustar el peso de las clases con class_weight='balanced' y ajustar el umbral de decisión para que detecte las cancelaciones realísticamente.

El modelo empezará a capturar las cancelaciones reales (subirá el Recall de la clase 1), dándote una herramienta funcional para el negocio.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score

# 1. Re-entrenar con balanceo de clases automático
modelo_rf_balanced = RandomForestClassifier(
    n_estimators=100,
    max_depth=6,
    class_weight='balanced', # Compensar el desbalanceo
    random_state=42
)
modelo_rf_balanced.fit(X_train, y_train)

# 2. Predecir probabilidades
y_proba_balanced = modelo_rf_balanced.predict_proba(X_test)[:, 1]

# 3. Aplicar un umbral de decisión adaptado (ej. 0.40 o 0.45 en vez de 0.50)
umbral = 0.42
y_pred_ajustado = (y_proba_balanced >= umbral).astype(int)

# 4. Evaluación corregida
print("=== INFORME CORREGIDO DEL MODELO ===")
print(classification_report(y_test, y_pred_ajustado))
print(f"Nuevo ROC-AUC: {roc_auc_score(y_test, y_proba_balanced):.4f}")

"""- Recall de Cancelaciones (0.79 / 79%): El modelo logra capturar 184 de las 232 cancelaciones reales. Ha dejado de ignorar la clase 1.

- Caída Drástica de la Precisión (0.15 / 15%): De cada 100 reservas que el modelo marca como "alta probabilidad de cancelación", solo 15 son reales y 85 son falsas alarmas.

- Colapso del Accuracy (35%): Al penalizar tanto los falsos positivos (clientes que no iban a cancelar pero el modelo dijo que sí), el rendimiento global del modelo se destruye.

- ROC-AUC (0.5887): Al ser menor a 0.60, confirma que las variables actuales (lead_time, importe_eur, etc.) no tienen suficiente fuerza por sí solas para separar adecuadamente ambos grupos mediante un Random Forest básico

Sigue siendo malo el modelo por lo que vamos a calcular un umbral concreto y no a ciegas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, precision_recall_curve, confusion_matrix

# =============================================================================
# 1. PREPARACIÓN DE DATOS (FEATURE ENGINEERING)
# =============================================================================
reservas['target_cancelada'] = (reservas['estado_clean'] == 'cancelada').astype(int)
reservas['mes_reserva'] = reservas['fecha_reserva_dt'].dt.month
reservas['dia_semana_reserva'] = reservas['fecha_reserva_dt'].dt.dayofweek
reservas['es_fin_semana'] = reservas['dia_semana_reserva'].isin([5, 6]).astype(int)

features = ['lead_time', 'importe_eur', 'mes_reserva', 'dia_semana_reserva', 'es_fin_semana']
X = reservas[features].fillna(0)
y = reservas['target_cancelada']

# Division Train / Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# =============================================================================
# 2. ENTRENAMIENTO Y CÁLCULO DE PROBABILIDADES
# =============================================================================
modelo_base = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42)
modelo_base.fit(X_train, y_train)

# Obtenemos la probabilidad continua de que la reserva sea cancelada (0.0 a 1.0)
y_proba = modelo_base.predict_proba(X_test)[:, 1]

# =============================================================================
# 3. BÚSQUEDA AUTOMÁTICA DEL UMBRAL ÓPTIMO (F1-SCORE)
# =============================================================================
precisions, recalls, thresholds = precision_recall_curve(y_test, y_proba)

# Calculamos F1-Score para cada umbral y seleccionamos el valor máximo
f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-10)
mejor_idx = np.argmax(f1_scores)
umbral_optimo = thresholds[mejor_idx]

# Predicción final aplicando el umbral encontrado
y_pred_optimo = (y_proba >= umbral_optimo).astype(int)

# =============================================================================
# 4. IMPRESIÓN DE RESULTADOS
# =============================================================================
print(f"=== UMBRAL ÓPTIMO DETECTADO: {umbral_optimo:.4f} ===")
print("\n=== INFORME DE CLASIFICACIÓN CORREGIDO ===")
print(classification_report(y_test, y_pred_optimo))
print(f"Área Bajo la Curva ROC (ROC-AUC): {roc_auc_score(y_test, y_proba):.4f}")

"""Al ajustar el umbral de decisión al punto óptimo de 0.1376, el modelo alcanza su máximo rendimiento balanceado dentro de las limitaciones de los datos actuales:

- Captura de Riesgo (Recall = 57%): El algoritmo logra identificar a tiempo a más de la mitad de los clientes que terminarán cancelando (132 de las 232 cancelaciones reales en la muestra de prueba). Esto representa una mejora sustancial frente al modelo inicial, que ignoraba por completo las cancelaciones.

- Tasa de Falsos Positivos (Precisión = 20%): Existe un margen de error elevado donde 4 de cada 5 reservas etiquetadas como "alto riesgo" corresponden en realidad a clientes que sí realizarán la actividad.

- Conclusión Técnica Final: El valor de ROC-AUC de 0.6071 confirma formalmente que el comportamiento del cliente no se explica únicamente con la antelación (lead_time) o el importe consumido (importe_eur). Existen factores externos no registrados en el dataset (como motivos personales, clima o país de origen) que influyen en la decisión de cancelar.

**DECISIONES DE NEGOCIO**

Dado que la precisión es del 20%, no es aconsejable aplicar medidas coercitivas o penalizaciones automáticas (como cobros por cancelación previa) a las reservas detectadas como "riesgo", ya que se estaría penalizando erróneamente a un 80% de clientes legítimos.

En su lugar, la estrategia debe orientarse a acciones de bajo impacto y alto valor agregado dirigidas de forma general a las reservas de alta antelación (más de 15 días):

- **Re-engagement suave:** Envíos automáticos de correo con la guía de la ciudad o recomendaciones de la actividad 10 días después de la reserva para mantener vivo el interés.

- **Confirmación activa**: Enviar un recordatorio con un botón de "Confirmar mi asistencia" 48 horas antes para liberar plazas de los clientes que ya sepan que no asistirán.

- **Overbooking prudente:** Permitir un margen extra de sobre-reserva en actividades de gran capacidad durante las temporadas con mayor volumen de compras anticipadas

## **Análisis de Origen vs. Destino**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# =============================================================================
# 1. EXTRACCIÓN Y LIMPIEZA DE ORIGEN Y DESTINO
# =============================================================================
# Extraemos la provincia/ciudad de origen desde la dirección del cliente
clientes['origen_cliente'] = clientes['direccion'].apply(
    lambda x: x.split(',')[-1].strip() if isinstance(x, str) and ',' in x else 'Desconocido'
)

# Obtenemos la relación única de user_id con el país del tour/evento (pais_ip)
destino_eventos = eventos.dropna(subset=['user_id', 'pais_ip']).drop_duplicates(subset=['user_id'])[['user_id', 'pais_ip']]

# Unimos la información de origen (clientes) y destino (eventos) a las reservas
df_flujos = reservas.merge(clientes[['user_id', 'origen_cliente']], on='user_id', how='left')
df_flujos = df_flujos.merge(destino_eventos.rename(columns={'pais_ip': 'pais_destino_tour'}), on='user_id', how='left')

# Limpiamos valores nulos
df_flujos['origen_cliente'] = df_flujos['origen_cliente'].fillna('Desconocido')
df_flujos['pais_destino_tour'] = df_flujos['pais_destino_tour'].fillna('Desconocido')

# =============================================================================
# 2. VOLUMEN DE RESERVAS: MATRIZ ORIGEN DE CLIENTES VS PAÍS DEL TOUR
# =============================================================================
matriz_volumen = pd.crosstab(
    index=df_flujos['origen_cliente'],
    columns=df_flujos['pais_destino_tour'],
    margins=True,
    margins_name='Total'
)

print("=== MATRIZ DE MATRICULACIONES Y VOLUMEN (ORIGEN VS DESTINO) ===")
print(matriz_volumen)




# =============================================================================
# 3. TASA DE CANCELACIÓN (%) POR FLUJO DE VIAJE (CORREGIDO)
# =============================================================================
matriz_cancelacion = pd.crosstab(
    index=df_flujos['origen_cliente'],
    columns=df_flujos['pais_destino_tour'],
    values=(df_flujos['estado_clean'] == 'cancelada').astype(int),
    aggfunc='mean'
) * 100

# Visualización mediante Mapa de Calor
plt.figure(figsize=(10, 6))
sns.heatmap(matriz_cancelacion, annot=True, fmt=".1f", cmap="OrRd", cbar_kws={'label': '% Cancelación'})
plt.title('Porcentaje de Cancelación por Origen del Cliente y País del Tour')
plt.xlabel('País de Destino (pais_ip)')
plt.ylabel('Ubicación de Origen (Dirección Cliente)')
plt.tight_layout()
plt.show()

"""**Concentración de Mercado (Destino)**

- Dominio del Mercado Nacional (España): Representa el destino principal para todas las provincias de origen, sumando 4.771 reservas (el 56.7% del total). Barcelona (528), Valencia (504) y Bilbao (493) lideran la demanda interna.

- México como Primer Destino Internacional: Acumula 1.057 reservas (12.5% del total), situándose por delante de otros mercados latinoamericanos como Argentina (778) y Colombia (638). Sevilla (126) y Barcelona (123) registran el mayor volumen hacia México.

- Demanda Residual en Europa: Francia (260) e Italia (140) muestran volúmenes significativamente más bajos en comparación con el continente americano.

**Comportamiento por Origen**

- Málaga lidera el volumen hacia Argentina: Aporta 113 reservas, distanciándose notablemente de la media de otras provincias (~75 reservas).

- Distribución Homogénea por Provincias: La demanda total por provincia emisora está muy equilibrada (entre 779 reservas de Madrid y 889 de Barcelona), lo que indica que la captación de usuarios no depende de una única región de origen.

**Análisis de Picos Extremos de Cancelación**

- Italia (Punto crítico puntual): Destaca el pico del 37.5% de cancelación en clientes de Zaragoza hacia Italia, seguido de Alicante hacia Francia (27.8%). Al ser destinos europeos de media distancia, suele deberse a cancelaciones de última hora por cambios de vuelos low-cost o escapadas de fin de semana canceladas por clima/agenda.

- Latinoamérica (Riesgo estructural por distancia): Los viajes de larga distancia muestran tasas elevadas y sostenidas. Argentina registra cancelaciones por encima del 20% en Albacete (23.2%), Alicante (21.4%), Madrid (20.0%) y Sevilla (21.0%). Colombia roza el 23.0% en reservas desde Sevilla y 21.9% desde Málaga.

**Comportamiento en Destinos Masivos (España y México)**

- España (Estabilidad Operativa): El destino nacional presenta las tasas de cancelación más bajas y estables (entre 9.8% y 14.1%). Aunque concentra el 56.7% del volumen total, su riesgo porcentual es bajo.

- México (Fuga constante en volumen alto): Siendo el segundo destino en reservas, mantiene una tasa de cancelación considerable (entre 12.8% y 23.1%, destacando Valencia con un 23.1%). Al cruzarlo con el volumen previo (1.057 reservas), representa una pérdida económica muy alta.

**FLUJOS ORIGEN DESTINO**

- **Patrón de Larga Distancia vs. Riesgo:** A mayor distancia transatlántica (Argentina, Colombia, Chile, México), la tasa de cancelación media se incrementa entre 5 y 10 puntos porcentuales en comparación con los tours nacionales en España.

- **Destinos de Escapada en Europa:** Mercados como Italia o Francia muestran volatilidades extremas en provincias específicas, condicionadas por la flexibilidad de los medios de transporte de corto radio.


- **Fianza/Depósito Específico por Destino:** Aplicar el sistema de depósitos escalonados (20% no reembolsable) principalmente en las reservas dirigidas a Latinoamérica (Argentina, Colombia, México) realizadas con más de 15 días de antelación.

- **Políticas Flexibles pero Controladas en Europa:** Para tours en Francia e Italia, implementar avisos de confirmación vía WhatsApp a las 48h (en lugar de penalizaciones económicas) para reasignar rápido las plazas procedentes de escapadas canceladas.

- **Optimización en Mercado Nacional:** Mantener las políticas actuales en España, ya que la tasa de cancelación es baja (10-14%) y cualquier restricción extra frenaría la conversión del principal motor de ingresos.

## **Categorizar los Tours con NLP Básica**
"""

import pandas as pd

# 1. Reglas de categorización basadas en el texto de 'descripcion'
def categorizar_tour(texto):
    if not isinstance(texto, str):
        return 'Otros'

    texto_lower = texto.lower()
    if 'free tour' in texto_lower:
        return 'Free Tour'
    elif 'sin colas' in texto_lower or 'entrada' in texto_lower:
        return 'Entradas / Accesos'
    elif 'atardecer' in texto_lower or 'nocturn' in texto_lower or 'romántic' in texto_lower:
        return 'Experiencia / Nocturno'
    elif 'visita guiada' in texto_lower or 'paseo' in texto_lower:
        return 'Visita Guiada'
    else:
        return 'Tour Estándar'

# 2. Aplicar categorización en la tabla de tours
tours['categoria_tour'] = tours['descripcion'].apply(categorizar_tour)

# 3. Unir a la tabla de reservas para calcular la tasa de cancelación por tipo de tour
reservas_nlp = reservas.merge(tours[['tour_id', 'categoria_tour']], on='tour_id', how='left')

resumen_categoria = reservas_nlp.groupby('categoria_tour').agg(
    total_reservas=('reserva_id', 'count'),
    tasa_cancelacion_pct=('estado_clean', lambda x: (x == 'cancelada').mean() * 100)
).reset_index().sort_values(by='tasa_cancelacion_pct', ascending=False)

print("=== CANCELACIONES POR CATEGORÍA DE TOUR (NLP) ===")
print(resumen_categoria.to_string(index=False))

"""**Análisis del Comportamiento por Categoría**

- **Experiencia / Nocturno (14.70%) y Tour Estándar (14.43%):** Encabezan la tasa de cancelación. Las actividades nocturnas o románticas suelen ser más sensibles a imprevistos de última hora (cansancio tras el día, cambios de planes en la cena o clima nocturno).

- **Free Tour (13.57%): Mantiene una tasa media-alta**. Aunque el coste inicial es cero, la falta de compromiso económico anticipado suele generar cancelaciones voluntarias o no asistencias (no-shows).

- **Entradas / Accesos (12.57%) y Visita Guiada (12.38%):** Presentan las tasas más bajas. Al implicar la reserva de boletos a monumentos o itinerarios guiados formales, el usuario percibe un mayor valor y compromiso con la actividad.

**El tipo de tour** (Free Tour, Entradas, Experiencias Nocturnas) no marca diferencias sustanciales en la tasa de cancelación (todas entre el 12.3% y el 14.7%).
"""